export enum Env {
  PORT = 'PORT',
  DB_HOST = 'POSTGRES_HOST',
  DB_PORT = 'POSTGRES_PORT',
  DB_NAME = 'POSTGRES_DB',
  DB_USER = 'POSTGRES_USER',
  DB_PASSWORD = 'POSTGRES_PASSWORD',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION',
}
